services:
  python:
    build: .
    env_file:
      - ./.dev.vars
    volumes:
      - ./main.dev.1.py:/myproject/main.py:ro
      - ./public/:/myproject/public/
      - ./static/:/myproject/static/:ro
      - ./templates/:/myproject/templates/:ro
      - ./test/:/myproject/test/:ro
    command: python3 /myproject/main.py